/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Data.*;
import Logging.*;
import Parqueadero.ClassParametrosSimulacion;
import Parqueadero.ParqueaderoBESA.ICallbackGUI;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.*;

/**
 *
 * @author Mauricio
 */
public class MainFrame extends javax.swing.JFrame 
{
    private ICallbackGUI  callback;
    private MapPanel mapPanel;
    private int numeroPisos;
    private int pisoActual;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame(ICallbackGUI _callback, int _size) 
    {
        initComponents();
        numeroPisos = 1;
        callback = _callback;
        pisoActual = 1;
        dummyPannel.setBorder(BorderFactory.createLineBorder(Color.black));
        LoadImageToButton(jButtonLeft, "Files\\arrowLeft.png");
        LoadImageToButton(jButtonRight, "Files\\arrowRight.png");
        jButtonLeft.setEnabled(false);
        jButtonRight.setEnabled(false);
        
        SetMapPanel(_size);
    }

    public void RedibujarMapa(ClassElemento[][] listaElementos, List<ClassElemento> listaAgentes)
    {
        mapPanel.RedibujarMapa(listaElementos, listaAgentes);
    }

    private void SetMapPanel(int size)
    { 
        mapPanel = new MapPanel(size);
        mapPanel.setLocation(dummyPannel.getLocation());
        mapPanel.setPreferredSize(dummyPannel.getSize());
        
        this.add(mapPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        this.remove(dummyPannel);
    }
    
    private void ActualizarBotones()
    {
       jButtonLeft.setEnabled(false);
       jButtonRight.setEnabled(false);
    
       if (pisoActual > 1)
           jButtonLeft.setEnabled(true);
       if (numeroPisos > pisoActual)
           jButtonRight.setEnabled(true);
       
       jLabelPisoInfo.setText("Piso Actual: PISO " + pisoActual);
    }
    
    private void LoadImageToButton(JButton button, String filePath)
    {
        try 
        {
            Image img = ImageIO.read(new File(filePath));
            img = img.getScaledInstance(button.getWidth(), button.getHeight(), Image.SCALE_DEFAULT);
            button.setIcon(new ImageIcon(img));
        } 
        catch (IOException ex) 
        {
            ClassLogger.LogMsg("Excepcion no controlada en la aplicacion: " + ex.toString(), LogLevel.ERROR);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dummyPannel = new javax.swing.JPanel();
        jTextCantidadCarros = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonIniciar = new javax.swing.JButton();
        jButtonRight = new javax.swing.JButton();
        jButtonLeft = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextCantidadPeatones = new javax.swing.JTextField();
        jLabelPisoInfo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextCantidadPisos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dummyPannel.setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout dummyPannelLayout = new javax.swing.GroupLayout(dummyPannel);
        dummyPannel.setLayout(dummyPannelLayout);
        dummyPannelLayout.setHorizontalGroup(
            dummyPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        dummyPannelLayout.setVerticalGroup(
            dummyPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(dummyPannel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTextCantidadCarros.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextCantidadCarros.setText("1");
        getContentPane().add(jTextCantidadCarros, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 250, 72, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Universidad Javeriana");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 71, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Peatones por Carro");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Facultad de Ingeniería");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(714, 101, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Maestría en Ingeniería de Sistemas y Computación");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 131, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Simulador de Parqueaderos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(667, 206, -1, -1));

        jButtonIniciar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonIniciar.setText("Iniciar");
        jButtonIniciar.setActionCommand("");
        jButtonIniciar.setAutoscrolls(true);
        jButtonIniciar.setContentAreaFilled(false);
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 385, 127, 46));

        jButtonRight.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonRight.setAutoscrolls(true);
        jButtonRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRightActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 480, 70, 60));

        jButtonLeft.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonLeft.setAutoscrolls(true);
        jButtonLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeftActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, 70, 60));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Cantidad Carros");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, -1, 30));

        jTextCantidadPeatones.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextCantidadPeatones.setText("1");
        getContentPane().add(jTextCantidadPeatones, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 290, 72, -1));

        jLabelPisoInfo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPisoInfo.setText("Piso actual: NINGUNO");
        getContentPane().add(jLabelPisoInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 570, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Cantidad Pisos");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, -1, 30));

        jTextCantidadPisos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextCantidadPisos.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextCantidadPisos.setText("5");
        jTextCantidadPisos.setToolTipText("");
        getContentPane().add(jTextCantidadPisos, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 330, 72, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        ClassLogger.LogMsg("Generando accion de callback - boton iniciar");
        jButtonIniciar.setEnabled(false);
        
        
        try
        {
            int numeroVehiculos = Integer.parseInt(jTextCantidadCarros.getText());
            int numeroOcupantes = Integer.parseInt(jTextCantidadPeatones.getText());
            numeroPisos = Integer.parseInt(jTextCantidadPisos.getText());        
            
            ClassParametrosSimulacion parametros = new ClassParametrosSimulacion();
            parametros.numeroVehiculos = numeroVehiculos;
            parametros.numeroOcupantes = numeroOcupantes;
            parametros.numeroPisos = numeroPisos;
            
            //Llama a la funcion de inicializacion del GUI
            callback.CallbackIniciar(parametros);
            
            
            
            //Actualizacion de botones
            ActualizarBotones();
            callback.CallbackUpdatePiso(pisoActual);
        }
        catch (NumberFormatException ex)
        {
            ClassLogger.ShowInfoBox(ex.toString(), "Exepcion en la aplicacion");
        }
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void jButtonLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeftActionPerformed
        // TODO add your handling code here:
        pisoActual--;
        ActualizarBotones();
        callback.CallbackUpdatePiso(pisoActual);
    }//GEN-LAST:event_jButtonLeftActionPerformed

    private void jButtonRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRightActionPerformed
        // TODO add your handling code here:
        pisoActual++;
        ActualizarBotones();
        callback.CallbackUpdatePiso(pisoActual);
    }//GEN-LAST:event_jButtonRightActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dummyPannel;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JButton jButtonLeft;
    private javax.swing.JButton jButtonRight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelPisoInfo;
    private javax.swing.JTextField jTextCantidadCarros;
    private javax.swing.JTextField jTextCantidadPeatones;
    private javax.swing.JTextField jTextCantidadPisos;
    // End of variables declaration//GEN-END:variables
}
